version: "3.8"

services:
  app:
    container_name: movieGo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env

  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    entrypoint: ["migrate", "-path=/migrations/", "-database=${MOVIEGO_DB_DSN}"]
    command: ["up"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
    

  postgres:
    container_name: postgres_movieGo
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movieGo
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: